## Handling Rows And Indexes

> Indexes of data is one of the important topics in the data handling.   
> Here will learn about how to see the index numbers and how to set a particular column as index.

In [1]:
import pandas as pd

data = pd.read_csv('E:/DATA_SCIENCE/DS/DataScience/data/nyc_flights.csv')
display(data)

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,6,30,940,15,1216,-4,VX,N626VA,407,JFK,LAX,313,2475,9,40
1,2013,5,7,1657,-3,2104,10,DL,N3760C,329,JFK,SJU,216,1598,16,57
2,2013,12,8,859,-1,1238,11,DL,N712TW,422,JFK,LAX,376,2475,8,59
3,2013,5,14,1841,-4,2122,-34,DL,N914DL,2391,JFK,TPA,135,1005,18,41
4,2013,7,21,1102,-3,1230,-8,9E,N823AY,3652,LGA,ORF,50,296,11,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32730,2013,10,8,752,-8,921,-28,9E,N8505Q,3611,JFK,PIT,63,340,7,52
32731,2013,7,7,812,-3,1043,8,DL,N6713Y,1429,JFK,LAS,286,2248,8,12
32732,2013,9,3,1057,-1,1319,-19,UA,N77871,1545,EWR,IAH,180,1400,10,57
32733,2013,10,15,844,56,1045,60,B6,N258JB,1273,JFK,CHS,93,636,8,44
32734,2013,3,28,1813,-3,1942,-23,UA,N36272,1053,EWR,CLE,59,404,18,13

### 1. index perameter
> Returns list of index numbers

In [2]:
print(data.index)

print(type(data.index))

RangeIndex(start=0, stop=32735, step=1)
<class 'pandas.core.indexes.range.RangeIndex'>

### 2. set_index() function
> To set a specific column value as index numbers.

In [3]:
data.set_index("day", inplace=True)
display(data)

,year,month,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
day,,,,,,,,,,,,,,,
30,2013,6,940,15,1216,-4,VX,N626VA,407,JFK,LAX,313,2475,9,40
7,2013,5,1657,-3,2104,10,DL,N3760C,329,JFK,SJU,216,1598,16,57
8,2013,12,859,-1,1238,11,DL,N712TW,422,JFK,LAX,376,2475,8,59
14,2013,5,1841,-4,2122,-34,DL,N914DL,2391,JFK,TPA,135,1005,18,41
21,2013,7,1102,-3,1230,-8,9E,N823AY,3652,LGA,ORF,50,296,11,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,2013,10,752,-8,921,-28,9E,N8505Q,3611,JFK,PIT,63,340,7,52
7,2013,7,812,-3,1043,8,DL,N6713Y,1429,JFK,LAS,286,2248,8,12
3,2013,9,1057,-1,1319,-19,UA,N77871,1545,EWR,IAH,180,1400,10,57
15,2013,10,844,56,1045,60,B6,N258JB,1273,JFK,CHS,93,636,8,44
28,2013,3,1813,-3,1942,-23,UA,N36272,1053,EWR,CLE,59,404,18,13

In [4]:
data.set_index(["dep_time", "dep_delay"], inplace=True)
display(data)

,,year,month,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
dep_time,dep_delay,,,,,,,,,,,,,
940,15,2013,6,1216,-4,VX,N626VA,407,JFK,LAX,313,2475,9,40
1657,-3,2013,5,2104,10,DL,N3760C,329,JFK,SJU,216,1598,16,57
859,-1,2013,12,1238,11,DL,N712TW,422,JFK,LAX,376,2475,8,59
1841,-4,2013,5,2122,-34,DL,N914DL,2391,JFK,TPA,135,1005,18,41
1102,-3,2013,7,1230,-8,9E,N823AY,3652,LGA,ORF,50,296,11,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,-8,2013,10,921,-28,9E,N8505Q,3611,JFK,PIT,63,340,7,52
812,-3,2013,7,1043,8,DL,N6713Y,1429,JFK,LAS,286,2248,8,12
1057,-1,2013,9,1319,-19,UA,N77871,1545,EWR,IAH,180,1400,10,57
844,56,2013,10,1045,60,B6,N258JB,1273,JFK,CHS,93,636,8,44
1813,-3,2013,3,1942,-23,UA,N36272,1053,EWR,CLE,59,404,18,13

### 4. drop() function
> Drop some specific rows based on index numbers.

In [5]:
import pandas as pd

data = pd.read_csv('E:/DATA_SCIENCE/DS/DataScience/data/nyc_flights.csv')

data.drop(1, inplace=True)
display(data)

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,6,30,940,15,1216,-4,VX,N626VA,407,JFK,LAX,313,2475,9,40
2,2013,12,8,859,-1,1238,11,DL,N712TW,422,JFK,LAX,376,2475,8,59
3,2013,5,14,1841,-4,2122,-34,DL,N914DL,2391,JFK,TPA,135,1005,18,41
4,2013,7,21,1102,-3,1230,-8,9E,N823AY,3652,LGA,ORF,50,296,11,2
5,2013,1,1,1817,-3,2008,3,AA,N3AXAA,353,LGA,ORD,138,733,18,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32730,2013,10,8,752,-8,921,-28,9E,N8505Q,3611,JFK,PIT,63,340,7,52
32731,2013,7,7,812,-3,1043,8,DL,N6713Y,1429,JFK,LAS,286,2248,8,12
32732,2013,9,3,1057,-1,1319,-19,UA,N77871,1545,EWR,IAH,180,1400,10,57
32733,2013,10,15,844,56,1045,60,B6,N258JB,1273,JFK,CHS,93,636,8,44
32734,2013,3,28,1813,-3,1942,-23,UA,N36272,1053,EWR,CLE,59,404,18,13

In [6]:
data.drop([2,3,4,6], inplace=True)
display(data)

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,6,30,940,15,1216,-4,VX,N626VA,407,JFK,LAX,313,2475,9,40
5,2013,1,1,1817,-3,2008,3,AA,N3AXAA,353,LGA,ORD,138,733,18,17
7,2013,8,13,1920,85,2032,71,B6,N284JB,1407,JFK,IAD,48,228,19,20
8,2013,9,26,725,-10,1027,-8,AA,N3FSAA,2279,LGA,MIA,148,1096,7,25
9,2013,4,30,1323,62,1549,60,EV,N12163,4162,EWR,JAX,110,820,13,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32730,2013,10,8,752,-8,921,-28,9E,N8505Q,3611,JFK,PIT,63,340,7,52
32731,2013,7,7,812,-3,1043,8,DL,N6713Y,1429,JFK,LAS,286,2248,8,12
32732,2013,9,3,1057,-1,1319,-19,UA,N77871,1545,EWR,IAH,180,1400,10,57
32733,2013,10,15,844,56,1045,60,B6,N258JB,1273,JFK,CHS,93,636,8,44
32734,2013,3,28,1813,-3,1942,-23,UA,N36272,1053,EWR,CLE,59,404,18,13

In [7]:
print(data.index)

Int64Index([    0,     5,     7,     8,     9,    10,    11,    12,    13,
               14,
            ...
            32725, 32726, 32727, 32728, 32729, 32730, 32731, 32732, 32733,
            32734],
           dtype='int64', length=32730)