# OrdinalEncoder

### 1. Data Loading

In [23]:

import pandas as pd

# Loading Data
data = pd.read_csv('E:/DS/DataScience/Dealing_With_categorical_Data/data/Nutritional_Content_of_Cereals/cereal.csv')
display(data.head())

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,String,Categorical,Categorical,Int,Int,Int,Int,Float,Float,Int,Int,Int,Int,Float,Float,Float
1,100% Bran,N,C,70,4,1,130,10,5,6,280,25,3,1,0.33,68.402973
2,100% Natural Bran,Q,C,120,3,5,15,2,8,8,135,0,3,1,1,33.983679
3,All-Bran,K,C,70,4,1,260,9,7,5,320,25,3,1,0.33,59.425505
4,All-Bran with Extra Fiber,K,C,50,4,0,140,14,8,0,330,25,3,1,0.5,93.704912

In [24]:
data.drop(0, inplace=True)
data.dropna(inplace=True)

data.reset_index(drop=True, inplace=True)
display(data)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10,5,6,280,25,3,1,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2,8,8,135,0,3,1,1,33.983679
2,All-Bran,K,C,70,4,1,260,9,7,5,320,25,3,1,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14,8,0,330,25,3,1,0.5,93.704912
4,Almond Delight,R,C,110,2,2,200,1,14,8,-1,25,3,1,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Triples,G,C,110,2,1,250,0,21,3,60,25,3,1,0.75,39.106174
70,Trix,G,C,110,1,1,140,0,13,12,25,25,2,1,1,27.753301
71,Wheat Chex,R,C,100,3,1,230,3,17,3,115,25,1,1,0.67,49.787445
72,Wheaties,G,C,100,3,1,200,3,17,3,110,25,1,1,1,51.592193
73,Wheaties Honey Gold,G,C,110,2,1,200,1,16,8,60,25,1,1,0.75,36.187559

In [25]:
display(data.type.unique())
display(data.mfr.unique())

array(['C', 'H'], dtype=object)

array(['N', 'Q', 'K', 'R', 'G', 'P', 'A'], dtype=object)

### 2. Encoding

In [26]:
type_labels = {'C': 1, 'H': 2}

data["type"] = data["type"].replace(type_labels)

display(data)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,1,70,4,1,130,10,5,6,280,25,3,1,0.33,68.402973
1,100% Natural Bran,Q,1,120,3,5,15,2,8,8,135,0,3,1,1,33.983679
2,All-Bran,K,1,70,4,1,260,9,7,5,320,25,3,1,0.33,59.425505
3,All-Bran with Extra Fiber,K,1,50,4,0,140,14,8,0,330,25,3,1,0.5,93.704912
4,Almond Delight,R,1,110,2,2,200,1,14,8,-1,25,3,1,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Triples,G,1,110,2,1,250,0,21,3,60,25,3,1,0.75,39.106174
70,Trix,G,1,110,1,1,140,0,13,12,25,25,2,1,1,27.753301
71,Wheat Chex,R,1,100,3,1,230,3,17,3,115,25,1,1,0.67,49.787445
72,Wheaties,G,1,100,3,1,200,3,17,3,110,25,1,1,1,51.592193
73,Wheaties Honey Gold,G,1,110,2,1,200,1,16,8,60,25,1,1,0.75,36.187559

In [29]:
from sklearn.preprocessing import OrdinalEncoder

mfr_labels = ['Q', 'K', 'R', 'G', 'P', 'N', 'A']

ordenc = OrdinalEncoder( categories= [mfr_labels] )

ordenc.fit(data[['mfr']])

data['mfr'] = ordenc.transform(data[['mfr']])

In [30]:
display(data)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,mrf
0,100% Bran,5.0,1,70,4,1,130,10,5,6,280,25,3,1,0.33,68.402973,5.0
1,100% Natural Bran,0.0,1,120,3,5,15,2,8,8,135,0,3,1,1,33.983679,0.0
2,All-Bran,1.0,1,70,4,1,260,9,7,5,320,25,3,1,0.33,59.425505,1.0
3,All-Bran with Extra Fiber,1.0,1,50,4,0,140,14,8,0,330,25,3,1,0.5,93.704912,1.0
4,Almond Delight,2.0,1,110,2,2,200,1,14,8,-1,25,3,1,0.75,34.384843,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Triples,3.0,1,110,2,1,250,0,21,3,60,25,3,1,0.75,39.106174,3.0
70,Trix,3.0,1,110,1,1,140,0,13,12,25,25,2,1,1,27.753301,3.0
71,Wheat Chex,2.0,1,100,3,1,230,3,17,3,115,25,1,1,0.67,49.787445,2.0
72,Wheaties,3.0,1,100,3,1,200,3,17,3,110,25,1,1,1,51.592193,3.0
73,Wheaties Honey Gold,3.0,1,110,2,1,200,1,16,8,60,25,1,1,0.75,36.187559,3.0